### ISSUE TITLE
support `if (__pkg_test__)` 

### ISSUE THREAD

**Issue by cbm755** [apjanke/octave-testify#32]
How about returning a T/F boolean if `nargout == 1`?  And `NFAIL` for `nargout > 1`?

```
-- SUCCESS = __pkg_test__ (...)
 -- [NFAIL, __INFO__] = __pkg_test__ (...)
```

That's what we do in Doctest.  In principle one can `if (__pkg_test__)` to mean "if successfully ran tests".

**Comment by cbm755** [comment]
I did this for `runtests` in #38.

**Comment by apjanke** [comment]
Consistency is good. Let's do it.

**Comment by apjanke** [comment]
Done in https://github.com/apjanke/octave-testify/commit/c8d7b93509118b72577ebefa756ca2e0a2646720.
