### ISSUE TITLE
BistRunResult:plus has bug with no_tests list

### ISSUE THREAD

**Issue by cbm755** [apjanke/octave-testify#36]
In `runtests`, it seems that `rslts.files_with_no_tests` seems to fill up just as `rslts.with_tests` does.  This seems to happen following `rslts += rslt;`

Is that operation well-defined for structs?  Seems... magical.

**Comment by cbm755** [comment]
Oh, maybe `rslts` is an object.  In that case, looks like a bug in the `plus` method?

**Comment by apjanke** [comment]
`rslt` isn't a struct; it's a `octave.test.internal.BistRunResult` object, and `BistRunResult` [provides an overload for `plus`](https://github.com/apjanke/octave-testify/blob/8aa0b903df13c393c20f848bd35c56929a4253f2/inst/%2Boctave/%2Btest/%2Binternal/BistRunResult.m#L90-L112) that does this work.

**Comment by cbm755** [comment]
found it, sending silly patch...

**Comment by apjanke** [comment]
Ahh, I bet I know what your patch is going to be. :)
