### ISSUE TITLE
`x.y.z~` not currently recommended version string

### ISSUE THREAD

**Issue by cbm755** [apjanke/octave-testify#61]
Someday we can have nice things but not yet ;-)   (upstream issue https://savannah.gnu.org/bugs/?55838)

```
compare_versions ('0.4.0~', '0.4.0', '<')
ans = 0
```

This is why I recommended `0.3.0+` following the release of `0.3.0` and before `0.4.0`.

**Comment by apjanke** [comment]
D'oh! Changed back in https://github.com/apjanke/octave-testify/commit/6be080e577461cd336b154aaca20dac38e13b880.
