### ISSUE TITLE
Make dependency on doctest optional?

### ISSUE THREAD

**Issue by mtmiller** [apjanke/octave-testify#65]
How would you feel about dropping the `Depends: doctest` and making it an optional dependency? It's only used as an option, could be detected at runtime and raise an error if the function isn't found.

**Comment by apjanke** [comment]
I think that's fine.

We could demote the `Depends:` to a `Suggested:` to still indicate the relationship but not actually require it, right?

**Comment by apjanke** [comment]
Done in https://github.com/apjanke/octave-testify/commit/0452aa33e9608e6e75f83178ff61a3743da574c8.
