### ISSUE TITLE
runtests fails with error: 'isfolder' undefined

### ISSUE THREAD

**Issue by cbm755** [apjanke/octave-testify#7]
```octave
>> runtests .
error: 'isfolder' undefined near line 42 column 31
error: called from
    runtests at line 42 column 5
```

Tested on both Octave 4.2.1 and Octave dev tip (6.0).

This is 0.1.0, haven't tried master yet...

**Comment by cbm755** [comment]
Same on master branch

**Comment by cbm755** [comment]
Maybe my Octave is too old, I saw this warning when using 6.0.0:
```
warning: isdir is obsolete; use isfolder or dir_in_loadpath instead
```
So I'm guessing this works fine with dev Octave: is that intended?  Maybe this needs `Depends: octave (>= 6.0.0)` (or whatever the minimum is) in the DESCRIPTION file?

**Comment by apjanke** [comment]
`isfolder` was introduced in Octave 5.1.0.

For now, it's my intention for this to work on Octave 4.4.1 as well. I'll add a back-compatibility shim.

**Comment by apjanke** [comment]
Added a compatibility shim in https://github.com/apjanke/octave-testify/commit/27b2d31f604aa103cd70db1465f32874bee1e8dc, but I don't have an older version of Octave to test it on. Could you test?

**Comment by cbm755** [comment]
No warnings about isfolder, but I get:
```
octave:8> runtests2 .
Processing files in /home/cbm/src/octsympy/octsympy.git/inst:

  assume.m .................................................... PASS     18/18  
  assumptions.m ............................................... PASS     13/13  
  catalan.m ................................................... PASS      3/3   
  cell2sym.m .................................................. PASS      2/2   
  digits.m .................................................... PASS      1/1   
  dirac.m ..................................................... PASS      6/6   
error: 'files_with_tests' undefined near line 93 column 44
error: called from
    get.files_with_no_tests at line 93 column 11
    runtests2>run_all_tests at line 121 column 41
    runtests2 at line 71 column 11
octave:8> 
```

**Comment by apjanke** [comment]
Dumb unrelated bug I introduced recently. Will fix later tonight.

Closing this one as fixed.

**Comment by apjanke** [comment]
Fixed that newly introduced bug in https://github.com/apjanke/octave-testify/commit/1656827b0cb46ebcd3352393c12d6d51f0cd98eb.
